# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
  subscription_id = "773586ad-bb38-4d45-8c50-e4a3bb2021c8"
}

provider "random" {}

# We need the client config to get the Object ID of the user running Terragrunt
# This is required to set Key Vault access policies dynamically.
data "azurerm_client_config" "current" {}
